#!/usr/bin/env bash

CC="gcc"
SRC="main.c timer.c server.c client.c aux.h"
BIN="app"
OUT="-o $BIN"
CFLAGS="-std=c99 -Wall -pedantic -pthread -D_POSIX_C_SOURCE=199309L"

clear
echo
echo
printf "\033[33m%*s\033[39m\n\n" "${COLUMNS:-$(tput cols)}" '' | tr ' ' '*'
printf "  \033[33mMaker\033[39m (\033[33mCompiling\033[39m): \033[35m%s\033[39m (\033[36m%s\033[39m) => \033[34m%s\033[39m => \033[32m%s\033[39m\n" "$CC" "$CFLAGS" "$SRC" "$BIN"
$CC $CFLAGS $SRC $OUT
if [ "$1" == "run" ] ; then
    printf "  \033[33mMaker\033[39m (\033[33mRunning\033[39m): ./\033[32m%s\033[39m\n" $BIN
fi
printf "\n\033[33m%*s\033[39m\n" "${COLUMNS:-$(tput cols)}" '' | tr ' ' '*'
echo
if [ "$1" == "run" ] ; then
    ./$BIN
fi
echo
